services:
  user-service:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      MONGO_URI: ${MONGO_USER_URI}
      MONGO_DB: ${MONGO_USER_DB}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      user-db:
        condition: service_healthy

  upload-service:
    build:
      context: ./services/upload
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      MONGO_URI: ${MONGO_UPLOAD_URI}
      MONGO_DB: ${MONGO_UPLOAD_DB}
      JWT_SECRET: ${JWT_SECRET}
      NATS_URL: ${NATS_URL}
    depends_on:
      upload-db:
        condition: service_healthy
      user-service:
        condition: service_started
      nats:
        condition: service_started

  user-db:
    image: mongo:7
    command: ["mongod", "--quiet"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_USER_DB}
    volumes:
      - user-db-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\" > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 5

  upload-db:
    image: mongo:7
    command: ["mongod", "--quiet"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_UPLOAD_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_UPLOAD_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_UPLOAD_DB}
    volumes:
      - upload-db-data:/data/db
       - upload-videos:/data/videos
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\" > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

volumes:
  user-db-data:
  upload-db-data:
  upload-videos: